[package]
name = "fiitcoin"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.2"
log = "0.4.21"
rsa = { version = "0.9.6", features = ["sha2"]}
sha2 = "0.10.8"

[dev-dependencies]
rand = "0.8.5"

[dev.debug]
opt-level = 3
